import type { CampaignPosition, CampaignType } from "@/app/admin/campaigns/types";

export type CampaignTemplateCategory = "top_bar" | "modal" | "slide_in" | "others";

export type CampaignTemplate = {
  id: string;
  name: string;
  category: CampaignTemplateCategory;
  type: CampaignType;
  title: string;
  message: string;
  ctaText: string;
  ctaLink: string;
  primaryColor: string;
  textColor: string;
  backgroundStyle: string;
  position: CampaignPosition;
};

export const CAMPAIGN_TEMPLATE_CATEGORY_LABELS: Record<CampaignTemplateCategory, string> = {
  top_bar: "Top Bar",
  modal: "Modal",
  slide_in: "Slide-in",
  others: "Others",
};

export const CAMPAIGN_TEMPLATES: CampaignTemplate[] = [
  {
    id: "discount-offer",
    name: "Discount offer",
    category: "top_bar",
    type: "top_bar",
    title: "Save 25% this week",
    message: "Upgrade today and lock in your annual discount before Friday.",
    ctaText: "Claim discount",
    ctaLink: "/pricing",
    primaryColor: "#22d3ee",
    textColor: "#f8fafc",
    backgroundStyle: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
    position: "top",
  },
  {
    id: "free-trial",
    name: "Free trial",
    category: "top_bar",
    type: "top_bar",
    title: "Start your 14-day free trial",
    message: "No card needed. Try pro workflows and automation today.",
    ctaText: "Start trial",
    ctaLink: "/signup",
    primaryColor: "#38bdf8",
    textColor: "#f8fafc",
    backgroundStyle: "linear-gradient(135deg, #082f49 0%, #0f172a 100%)",
    position: "top",
  },
  {
    id: "announcement",
    name: "Announcement",
    category: "top_bar",
    type: "top_bar",
    title: "Important platform update",
    message: "We just improved campaign analytics with deeper funnel visibility.",
    ctaText: "Read update",
    ctaLink: "/blog",
    primaryColor: "#2dd4bf",
    textColor: "#f8fafc",
    backgroundStyle: "linear-gradient(135deg, #134e4a 0%, #0f172a 100%)",
    position: "top",
  },
  {
    id: "product-launch",
    name: "Product launch",
    category: "top_bar",
    type: "top_bar",
    title: "New: AI Campaign Optimizer",
    message: "Launch smarter onsite campaigns with one-click optimization.",
    ctaText: "Explore feature",
    ctaLink: "/app",
    primaryColor: "#34d399",
    textColor: "#f8fafc",
    backgroundStyle: "linear-gradient(135deg, #052e16 0%, #14532d 100%)",
    position: "top",
  },
  {
    id: "urgency-timer",
    name: "Urgency timer",
    category: "top_bar",
    type: "top_bar",
    title: "48 hours left to upgrade",
    message: "Get bonus onboarding and save on your first billing cycle.",
    ctaText: "Upgrade now",
    ctaLink: "/select-plan",
    primaryColor: "#f97316",
    textColor: "#fff7ed",
    backgroundStyle: "linear-gradient(135deg, #7c2d12 0%, #c2410c 100%)",
    position: "top",
  },
  {
    id: "newsletter-signup",
    name: "Newsletter signup",
    category: "modal",
    type: "modal",
    title: "Get growth playbooks weekly",
    message: "Join 12,000 founders getting conversion tactics every Tuesday.",
    ctaText: "Subscribe",
    ctaLink: "/signup",
    primaryColor: "#06b6d4",
    textColor: "#f8fafc",
    backgroundStyle: "linear-gradient(145deg, #111827 0%, #1f2937 100%)",
    position: "center",
  },
  {
    id: "exit-intent-offer",
    name: "Exit intent offer",
    category: "modal",
    type: "modal",
    title: "Wait - take 20% off",
    message: "Before you go, grab this discount and start improving conversions.",
    ctaText: "Get offer",
    ctaLink: "/pricing",
    primaryColor: "#22c55e",
    textColor: "#f0fdf4",
    backgroundStyle: "linear-gradient(145deg, #052e16 0%, #14532d 100%)",
    position: "center",
  },
  {
    id: "ebook-download",
    name: "Ebook download",
    category: "modal",
    type: "modal",
    title: "Download the CRO Ebook",
    message: "Learn proven onsite campaign formulas with real examples.",
    ctaText: "Download now",
    ctaLink: "/download",
    primaryColor: "#a78bfa",
    textColor: "#faf5ff",
    backgroundStyle: "linear-gradient(145deg, #312e81 0%, #4c1d95 100%)",
    position: "center",
  },
  {
    id: "webinar-invite",
    name: "Webinar invite",
    category: "modal",
    type: "modal",
    title: "Live webinar: double trial signups",
    message: "Reserve your seat and get the deck after the session.",
    ctaText: "Reserve spot",
    ctaLink: "/contact",
    primaryColor: "#f59e0b",
    textColor: "#fffbeb",
    backgroundStyle: "linear-gradient(145deg, #78350f 0%, #b45309 100%)",
    position: "center",
  },
  {
    id: "lead-magnet",
    name: "Lead magnet",
    category: "modal",
    type: "modal",
    title: "Steal our campaign swipe file",
    message: "Get 30 high-performing campaign examples in one PDF.",
    ctaText: "Get swipe file",
    ctaLink: "/download",
    primaryColor: "#ec4899",
    textColor: "#fdf2f8",
    backgroundStyle: "linear-gradient(145deg, #831843 0%, #be185d 100%)",
    position: "center",
  },
  {
    id: "feature-highlight",
    name: "Feature highlight",
    category: "slide_in",
    type: "slide_in",
    title: "New targeting filters are live",
    message: "Target by plan, role, and journey stage with zero code.",
    ctaText: "Try targeting",
    ctaLink: "/app",
    primaryColor: "#22d3ee",
    textColor: "#f0fdfa",
    backgroundStyle: "linear-gradient(145deg, #083344 0%, #0f766e 100%)",
    position: "bottom",
  },
  {
    id: "upgrade-prompt",
    name: "Upgrade prompt",
    category: "slide_in",
    type: "slide_in",
    title: "Unlock pro automations",
    message: "Upgrade now to trigger campaigns based on user behavior.",
    ctaText: "Upgrade",
    ctaLink: "/select-plan",
    primaryColor: "#10b981",
    textColor: "#ecfdf5",
    backgroundStyle: "linear-gradient(145deg, #064e3b 0%, #065f46 100%)",
    position: "bottom",
  },
  {
    id: "affiliate-promo",
    name: "Affiliate promo",
    category: "slide_in",
    type: "slide_in",
    title: "Earn recurring commissions",
    message: "Join the affiliate program and get paid for each referred upgrade.",
    ctaText: "Join program",
    ctaLink: "/contact",
    primaryColor: "#f43f5e",
    textColor: "#fff1f2",
    backgroundStyle: "linear-gradient(145deg, #4c0519 0%, #9f1239 100%)",
    position: "bottom",
  },
  {
    id: "survey",
    name: "Survey",
    category: "slide_in",
    type: "slide_in",
    title: "Help us improve",
    message: "Take a 1-minute survey and shape our next feature release.",
    ctaText: "Take survey",
    ctaLink: "/contact",
    primaryColor: "#3b82f6",
    textColor: "#eff6ff",
    backgroundStyle: "linear-gradient(145deg, #172554 0%, #1d4ed8 100%)",
    position: "bottom",
  },
  {
    id: "feedback-request",
    name: "Feedback request",
    category: "slide_in",
    type: "slide_in",
    title: "How is your experience so far?",
    message: "Share feedback so we can make campaigns faster and easier.",
    ctaText: "Share feedback",
    ctaLink: "/contact",
    primaryColor: "#eab308",
    textColor: "#fefce8",
    backgroundStyle: "linear-gradient(145deg, #422006 0%, #854d0e 100%)",
    position: "bottom",
  },
  {
    id: "countdown-deal",
    name: "Countdown deal",
    category: "others",
    type: "top_bar",
    title: "Deal expires tonight",
    message: "Upgrade before midnight to keep this limited launch price.",
    ctaText: "Lock my price",
    ctaLink: "/pricing",
    primaryColor: "#fb7185",
    textColor: "#fff1f2",
    backgroundStyle: "linear-gradient(145deg, #881337 0%, #be123c 100%)",
    position: "top",
  },
  {
    id: "seasonal-promo",
    name: "Seasonal promo",
    category: "others",
    type: "top_bar",
    title: "Seasonal savings are here",
    message: "Get your holiday growth bundle and save 30% this month.",
    ctaText: "See seasonal deal",
    ctaLink: "/pricing",
    primaryColor: "#60a5fa",
    textColor: "#eff6ff",
    backgroundStyle: "linear-gradient(145deg, #1e3a8a 0%, #1d4ed8 100%)",
    position: "top",
  },
  {
    id: "ab-test-variant",
    name: "AB test variant",
    category: "others",
    type: "modal",
    title: "Variant B: lower-friction CTA",
    message: "Try a softer ask to improve opt-in rate for first-time visitors.",
    ctaText: "Test this variant",
    ctaLink: "/app",
    primaryColor: "#14b8a6",
    textColor: "#f0fdfa",
    backgroundStyle: "linear-gradient(145deg, #134e4a 0%, #115e59 100%)",
    position: "center",
  },
  {
    id: "plan-upgrade",
    name: "Plan upgrade",
    category: "others",
    type: "modal",
    title: "Move to Scale for advanced analytics",
    message: "Unlock custom events, team seats, and SLA-backed support.",
    ctaText: "Compare plans",
    ctaLink: "/select-plan",
    primaryColor: "#4ade80",
    textColor: "#f0fdf4",
    backgroundStyle: "linear-gradient(145deg, #052e16 0%, #166534 100%)",
    position: "center",
  },
  {
    id: "new-feature-notice",
    name: "New feature notice",
    category: "others",
    type: "slide_in",
    title: "Fresh release: campaign templates",
    message: "Explore new high-converting templates and launch in minutes.",
    ctaText: "Open templates",
    ctaLink: "/admin/campaigns/templates",
    primaryColor: "#38bdf8",
    textColor: "#f0f9ff",
    backgroundStyle: "linear-gradient(145deg, #0c4a6e 0%, #075985 100%)",
    position: "bottom",
  },
  {
    id: "maintenance-alert",
    name: "Maintenance alert",
    category: "others",
    type: "top_bar",
    title: "Scheduled maintenance tonight",
    message: "Platform updates start at 11:00 PM UTC with minimal disruption.",
    ctaText: "See status",
    ctaLink: "/security",
    primaryColor: "#f59e0b",
    textColor: "#fffbeb",
    backgroundStyle: "linear-gradient(145deg, #451a03 0%, #92400e 100%)",
    position: "top",
  },
];

export const DEFAULT_CAMPAIGN_TEMPLATE_ID = CAMPAIGN_TEMPLATES[0]?.id ?? "discount-offer";

export function getCampaignTemplateById(id: string | null | undefined): CampaignTemplate {
  return CAMPAIGN_TEMPLATES.find((template) => template.id === id) ?? CAMPAIGN_TEMPLATES[0];
}
